client/src/test/java/com/aws/greengrass/cli/commands/LogsTest.java, server/src/main/java/com/aws/greengrass/cli/CLIService.java
=> fix: Correct version in client directory string

client/pom.xml, pom.xml, server/pom.xml, server/src/main/java/com/aws/greengrass/cli/CLIService.java
=> chore: update snapshot version to 2.1.0

client/pom.xml
=> chore(sdk): update sdk version

client/pom.xml
=> chore(ipc): use release version of ipc

.github/workflows/ci.yml, .github/workflows/externalPR.yml
=> build(ci): separate PR commenting to allow for pull requests

.github/workflows/ci.yml
Enable Github Action on Windows host
We want to run tests on Windows.
The names of the jobs are updated to reflect two builds. Please also update branch protection in order to merge this PR.
=> feat(windows): run github action on Windows as well

client/src/test/java/com/aws/greengrass/cli/commands/LogsTest.java
=> fix(windows): fix LogsTest

CHANGELOG.md, server/src/main/java/com/aws/greengrass/cli/CLIService.java
* Update the remaining Cli version number
* Also add an entry to the change log.
=> fix(windows): update remaining cli version

client/pom.xml, client/src/main/java/com/aws/greengrass/cli/util/logs/FileReader.java, client/src/main/java/com/aws/greengrass/cli/util/logs/LogEntry.java, client/src/main/java/com/aws/greengrass/cli/util/logs/LogQueue.java, client/src/main/java/com/aws/greengrass/cli/util/logs/impl/AggregationImpl.java, client/src/test/java/com/aws/greengrass/cli/util/logs/impl/AggregationImplTest.java
=> fix: do not quit when text logs are encountered (#124)

client/pom.xml, client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java, client/src/test/java/com/aws/greengrass/cli/commands/DeploymentCommandTest.java, client/src/test/resources/com/aws/greengrass/cli/commands/resource_limits.json
Enable local cli users to configure resource limits in the local deployment
unit test
=> feat(resource limits): add resource limit in the local cli

CHANGELOG.md, client/pom.xml, pom.xml, server/pom.xml, server/src/main/java/com/aws/greengrass/cli/CLIService.java
=> chore: update cli version to 2.3.0

client/src/main/java/com/aws/greengrass/cli/util/PlatformUtils.java
=> fix: close stream to avoid resource leak

server/pom.xml, server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
Removed redundant check which replaces empty group name with LOCAL_DEPLOYMENT_GROUP_NAME.
=> fix: remove redundant check

client/src/test/resources/com/aws/greengrass/cli/commands/resource_limits.json
=> fix(resource-limit): remove linux key

client/pom.xml
=> fix(resource-limit): use a newer device sdk snapshot

client/pom.xml, pom.xml, server/pom.xml, server/src/main/java/com/aws/greengrass/cli/CLIService.java
=> build: bump to 2.4.0 and remove version from the client zip

client/src/test/resources/com/aws/greengrass/cli/commands/resource_limits.json
=> refactor: change resource limits property from cpu to cpus

client/src/test/resources/com/aws/greengrass/cli/commands/resource_limits.json
=> refactor: change resource limits property from cpu to cpus (#135)

client/src/bin/greengrass-cli
=> fix: remove dependency on bash

client/pom.xml
=> chore(deps): update device SDK

client/pom.xml, client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java, client/src/test/java/com/aws/greengrass/cli/commands/DeploymentCommandTest.java, server/src/test/java/com/aws/greengrass/cli/IPCCliTest.java
User can specify windows user for runWith option via CLI
Unit tests
=> feat(windows): add windowsUser to cli

client/src/main/java/com/aws/greengrass/cli/commands/Logs.java
=> fix: require log directory input to list log files

client/src/bin/greengrass-cli.cmd
=> fix: add missing ending % in windows script

.github/workflows/ci.yml, pom.xml
=> ci: update commitlint version

client/pom.xml
Bump Device SDK version to 1.9.2.
=> chore(deps): update device SDK to 1.9.2

client/pom.xml, pom.xml, server/pom.xml
=> chore(deps): use latest device SDK

client/pom.xml, client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java, client/src/main/resources/com/aws/greengrass/cli/CLI_messages.properties, client/src/test/java/com/aws/greengrass/cli/commands/DeploymentCommandTest.java, pom.xml, server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java, server/src/test/java/com/aws/greengrass/cli/CLIEventStreamAgentTest.java
Add failure handling policy to both client side and server side
Unit test
=> feat(cli): add failure handling policy option

client/pom.xml
=> chore: use latest device sdk

client/pom.xml, client/src/main/java/com/aws/greengrass/cli/adapter/NucleusAdapterIpc.java, client/src/main/java/com/aws/greengrass/cli/adapter/impl/NucleusAdapterIpcClientImpl.java, client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java, pom.xml, server/pom.xml, server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
=> chore: update dependencies

client/pom.xml, client/src/main/java/com/aws/greengrass/cli/adapter/NucleusAdapterIpc.java, client/src/main/java/com/aws/greengrass/cli/adapter/impl/NucleusAdapterIpcClientImpl.java, client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java, pom.xml, server/pom.xml, server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
change nucleus versions to 2.12.0
update sdk depenency
=> prepare cli for 2.12 release

client/pom.xml, client/src/main/assembly/zip.xml
=> fix: remove old jackson core dependency

client/pom.xml
=> chore(deps): update device sdk to 1.20.1, logging 2.3.0

server/src/main/java/com/aws/greengrass/cli/CLIService.java
P213048579
Add check for null when getting component version from config. By design this should never happen, but we have seen this in rare situations.
The install phase of this component installs the Client binary, but this is not required for proper execution of the component itself, which is the CLI server. So if the install phase fails, we don't want the component to enter broken state.
Unit tested
=> Add check for null when getting component version from config
