aws-greengrass/aws-greengrass-cli

- .gitignore
- client/src/test/java/com/aws/greengrass/cli/commands/LogsTest.java
- client/src/test/java/com/aws/greengrass/cli/util/logs/impl/AggregationImplTest.java
Move the call to delete the temp directory at last.
When running unit tests on Windows, some tests can't delete the temp directory because some files are still open.
Those unit tests that failed because they can't delete the temp directory are passing now.
> Close the files first before deleting the temp directory.

- .github/workflows/ci.yml
- client/pom.xml
- client/src/main/java/com/aws/greengrass/cli/commands/PasswordCommand.java
- server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
- server/src/test/java/com/aws/greengrass/cli/CLIEventStreamAgentTest.java
If there is a certificate fingerprint set, then print that for the user to validate the certificate matches.
Added test and manually tested.
> feat(debugpassword): print certificate fingerprint in get-debug-password

- client/src/main/java/com/aws/greengrass/cli/commands/PasswordCommand.java
- server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
- server/src/test/java/com/aws/greengrass/cli/CLIEventStreamAgentTest.java
Windows doesn't show the certificate hash using SHA-256, only SHA-1. So we now provide both SHA-1 and SHA-256.
> fix: provide both sha1 and sha256 certificate hash

- .github/workflows/ci.yml
- client/src/main/java/com/aws/greengrass/cli/util/logs/FileReader.java
- client/src/main/java/com/aws/greengrass/cli/util/logs/impl/AggregationImpl.java
- client/src/test/java/com/aws/greengrass/cli/util/logs/impl/AggregationImplTest.java
- server/pom.xml
- server/src/test/java/com/aws/greengrass/cli/IPCCliTest.java
* Update Maven Nucleus dependency
* Enforce CI check on Windows 
* Lower code coverage threshold :(
* Enable previously disabled `IPCCliTest` tests
* Change `AggregationImpl` and `FileReader` so that the task pay attention to `isInterrupted`
> fix(windows): enforce tests for windows

- client/pom.xml
- pom.xml
- server/pom.xml
Update Cli version to 2.2.0 and also depends on Nucleus 2.2.0.
> chore(windows): cli version and nucleus dependency in pom.xml

- client/pom.xml
- client/src/main/java/com/aws/greengrass/cli/util/logs/FileReader.java
- client/src/main/java/com/aws/greengrass/cli/util/logs/LogEntry.java
- client/src/main/java/com/aws/greengrass/cli/util/logs/LogQueue.java
- client/src/main/java/com/aws/greengrass/cli/util/logs/impl/AggregationImpl.java
- client/src/test/java/com/aws/greengrass/cli/util/logs/impl/AggregationImplTest.java
#123 
Resolves #123 by treating text logs as if the whole log line is the message.
> fix: do not quit when text logs are encountered

- client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java
Handle the case where the runwith is null but the system limits is set
> fix: handle the case when runwith flag is null

- client/pom.xml
- pom.xml
- server/pom.xml
- server/src/main/java/com/aws/greengrass/cli/CLIService.java
- server/src/test/java/com/aws/greengrass/cli/CLIServiceTest.java
* Depend on Nucleus 2.5 which has the group lookup implemented
* Remove special case for Windows. 
Note that authorized group still doesn't work on windows even after this PR. We still need to update the named pipe access right. But that would require SDK changes and maybe Nucleus changes. However this PR is still needed. 
> feat(windows): support authorized windows groups

- server/src/main/java/com/aws/greengrass/cli/CLIService.java
- server/src/test/java/com/aws/greengrass/cli/CLIServiceTest.java
- server/src/test/java/com/aws/greengrass/cli/IPCCliTest.java
`Exec.isWindows` -> `PlatformResolver.isWindows`
Because `isWindows` field is duplicated. Removing the one in Exec.
> refactor: use PlatformResolver.isWindows

- client/src/bin/greengrass-cli.cmd
Necessary since customers access CLI via <ggroot>/bin/greengrass-cli.cmd which symlinks to the real path. The script itself needs to know the real path so that it can properly find the java jar path.
> fix(windows): handle symlinks when finding paths in cmd

- client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java
- client/src/main/resources/com/aws/greengrass/cli/CLI_messages.properties
- client/src/test/java/com/aws/greengrass/cli/commands/DeploymentCommandTest.java
- Allow setting both --runWith windowsUser and posixUser for the same component
- Update usage example
It is valid to set both.
CI
> fix: setting both runWith posixUser and windowsUser

- .github/workflows/ci.yml
- client/pom.xml
- server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
- server/src/test/java/com/aws/greengrass/cli/CLIEventStreamAgentTest.java
- server/src/test/java/com/aws/greengrass/cli/IPCCliTest.java
Adds authZ lookups using our standard `AuthorizationHandler`, thus enabling customer components to call CLI-based APIs in their own components after adding the necessary authorization policy. The CLI and CLI clients still short-circuit this logic and are allowed to perform any operation as before.
In the authorization policy, the resource is most often the component name which we're acting on. In other cases we use `*` since no more specific resource makes sense (ie. when listing components or deployments).
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> feat: add authZ lookup to allow non-CLI clients to call the APIs

- server/pom.xml
- server/src/test/java/com/aws/greengrass/cli/IPCCliTest.java
- server/src/test/resources/com/aws/greengrass/cli/ipc.yaml
Requires https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1229. Adds a test to validate the functionality of a component calling CLI implemented APIs.
> test: include test for component calling CLI IPC API

- client/src/main/java/com/aws/greengrass/cli/adapter/impl/NucleusAdapterIpcClientImpl.java
- When subscribing, set the option to receive all messages so that publishing from the CLI will result in the CLI's subscriber (if any) also receiving the message.
- fixes CLI so that it shuts down after it has subscribed and the stream closes for any reason, such as the Nucleus restarting.
- raise log level for EventStreamRPCConnection to only log warning+.
> fix: pubsub receive all messages, logging improvement

- CONTRIBUTING.md
- client/pom.xml
- client/src/main/java/com/aws/greengrass/cli/adapter/NucleusAdapterIpc.java
- client/src/main/java/com/aws/greengrass/cli/adapter/impl/NucleusAdapterIpcClientImpl.java
- client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java
- server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
- server/src/test/java/com/aws/greengrass/cli/CLIEventStreamAgentTest.java
Cli deployment list and status commands now have production ready information like detailed deployment status, error codes, etc. which makes the output more consistent with cloud.
Till now, Cli deployment command response was minimal and not consistent with cloud (not ready for prod)
Change was tested with manual verification and unit tests. Also manually verified Nucleus and Cli upgrade downgrade scenario.
1. Started with Nucleus and Cli 2.8.1 and verified Cli command outputs
2. Upgraded Nucleus and Cli to latest (with proposed changes) and verified Cli command outputs
3. Downgraded Nucleus and Cli back to 2.8.1 and verified Cli command outputs
**Any additional …
> feat: tune status and list command to be consistent with cloud

- CONTRIBUTING.md
- client/pom.xml
- client/src/main/java/com/aws/greengrass/cli/adapter/NucleusAdapterIpc.java
- client/src/main/java/com/aws/greengrass/cli/adapter/impl/NucleusAdapterIpcClientImpl.java
- client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java
- server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
- server/src/test/java/com/aws/greengrass/cli/CLIEventStreamAgentTest.java
This reverts commit 28a51440334e7d8c77823c06b06d42fb9b1cd570.
Some UATs were broken due to changing status command from reporting detailed deployment status SUCCESSFUL, instead of SUCCEEDED.
> revert: "feat: tune status and list command to be consistent with cloud (#171)"

- CONTRIBUTING.md
- client/pom.xml
- client/src/main/java/com/aws/greengrass/cli/adapter/NucleusAdapterIpc.java
- client/src/main/java/com/aws/greengrass/cli/adapter/impl/NucleusAdapterIpcClientImpl.java
- client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java
- server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
- server/src/test/java/com/aws/greengrass/cli/CLIEventStreamAgentTest.java
Cli deployment list and status commands now have production ready information like detailed deployment status, error codes, etc. which makes the output more consistent with cloud.
Current `status` command behavior:
```
<Deployment ID>: <Deployment Status> [SUCCEEDED, FAILED, IN_PROGRESS, CANCELED] 
```
Proposed behavior:
```
<Deployment ID>: <Deployment Status> [SUCCEEDED, FAILED, IN_PROGRESS, CANCELED] 
Created on: <Date and time in UTC when the deployment was created>
```
In case of a failed deployment, additional fields are
```
Detailed Status: <Detailed Deployment Status> [SUCCESSFUL, FAILED_ROLLBACK_NOT_REQUESTED, etc.]
Deployment Error Stack: [List of errors codes]
Deployment Error Types: [List of error types]
Failure Cause: …
```
> feat: tune status and list command + incompatibility fix

- client/src/main/java/com/aws/greengrass/cli/commands/DeploymentCommand.java
- server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
Add null checks for `detailedDeploymentStatus` field before converting to upper case and setting in `DeploymentStatusDetails` object.
When a deployment transitions into the IN_PROGRESS state, Nucleus publishes this state change but populates the `DeploymentStatusDetails` with an empty hash map causing the `detailedDeploymentStatus` field to be null. Additional null and empty checks need to be set in place before this field can be used by CLI.
> chore: add null check for detailed deployment status

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/externalPR.yml
> ci: upgrade github actions

- server/src/main/java/com/aws/greengrass/cli/CLIEventStreamAgent.java
- server/src/test/java/com/aws/greengrass/cli/IPCCliTest.java
Reject create deployment requests that contain an invalid thing group name (e.g. contains a `:`).
Server tests added
> fix: reject invalid thing group names

- .github/workflows/ci.yml
- client/pom.xml
Issue https://github.com/awslabs/aws-crt-java/issues/737 fixed in CRT v0.30.3
Java IoT Device SDK  includes this CRT version or above from v1.23.0: https://github.com/aws/aws-iot-device-sdk-java-v2/tree/v1.23.0. 
Our latest nucleus already uses this version. Bump the client sdk version in CLI to use the same. 
> chore: bump device sdk version

- server/src/main/java/com/aws/greengrass/cli/CLIService.java
P213048579
Restart the CLI component on auth change, rather than reinstall. 
Restart is needed because the auth is read once on startup and then cached in memory for the rest of the running phase.
Reinstall is not needed because the install phase only installs the CLI client executable, which is not changed by changes in auth.
Prevent unnecessary component reinstalls. For example, during the rollback of a deployment which installed the CLI, the configuration for the CLI is removed, notifying all subscriptions inside of the component, including these two.
Unit tested
By submitting this pull request, …
> fix: restart on auth change rather than reinstall
